# Generated by Django 3.1.1 on 2020-12-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=64)),
                ('empsal', models.FloatField()),
                ('empadr', models.CharField(max_length=64)),
            ],
        ),
    ]
