# Generated by Django 3.1.1 on 2021-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=200)),
                ('Lname', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Class', models.IntegerField()),
                ('Section', models.CharField(max_length=200)),
                ('Maths', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('Biology', models.IntegerField()),
                ('Stu_ID', models.IntegerField()),
                ('Email_ID', models.EmailField(max_length=200)),
            ],
        ),
    ]
